FROM canardconfit/puppeteer-docker:puppeteer-23.10.1-arm64 AS builder
WORKDIR /app

# Copy package.json and package-lock.json (if you have one)
COPY --chown=pptruser:pptruser  package*.json ./

# Install app dependencies
RUN npm install

# Copy the application source code
COPY --chown=pptruser:pptruser  . .

# Build the application using the build script defined in package.json
RUN npm run build

# --- Production Stage ---
FROM canardconfit/puppeteer-docker:puppeteer-23.10.1-arm64 AS production

# Set the working directory
WORKDIR /app

# Copy only the necessary files from the builder stage
COPY --chown=pptruser:pptruser  --from=builder /app/dist ./dist
COPY --chown=pptruser:pptruser  --from=builder /app/node_modules ./node_modules
COPY --chown=pptruser:pptruser  --from=builder /app/package*.json ./

# Set environment variables (if needed)
# ENV NODE_ENV production
# ENV PORT 3000

# Command to run the application
CMD ["node", "dist/index.js"]
