
FROM arm64v8/node:22-bullseye AS builder

WORKDIR /home/app-user/app

RUN apt-get update
RUN apt-get install chromium -y

ENV PUPPETEER_SKIP_CHROMIUM_DOWNLOAD=true
RUN npm install

RUN npm run build

# --- Production Stage ---
FROM arm64v8/node:22-bullseye

COPY --from=builder . .

RUN apt-get update && apt-get install -y chromium

ENV PUPPETEER_SKIP_CHROMIUM_DOWNLOAD=true
RUN npm install --omit=dev

CMD ["node", "dist/index.js"]
