# Ensure an up-to-date version of Chromium
# can be installed (solves Problem 2)
FROM node:22-bullseye AS builder

WORKDIR /home/app-user/app

COPY --chown=app-user:app-user . .

RUN apt-get update
RUN apt-get install chromium -y

ENV PUPPETEER_SKIP_CHROMIUM_DOWNLOAD=true
RUN npm install

RUN chown -R app-user:app-user

RUN npm run build

# --- Production Stage ---
FROM node:22-bullseye

COPY --from=builder . .

RUN apt-get update && apt-get install -y chromium

ENV PUPPETEER_SKIP_CHROMIUM_DOWNLOAD=true
RUN npm install --production

CMD ["node", "dist/index.js"]
