FROM mcr.microsoft.com/dotnet/sdk:8.0 AS build
WORKDIR /app
COPY *.csproj ./
RUN dotnet restore
COPY . ./
RUN dotnet publish -c Release -o out

RUN dotnet ef database update --project WebScraperDataIngestionAPI.csproj --startup-project WebScraperDataIngestionAPI.csproj 

FROM mcr.microsoft.com/dotnet/aspnet:8.0
WORKDIR /app
COPY --from=build /app/out ./
EXPOSE 80
ENTRYPOINT ["dotnet", "WebScraperDataIngestionAPI.dll"]
