services:
  app:
    build:
      context: .
      dockerfile: dockerfile
    image: api
    depends_on:
      - db
    environment:
      DATABASE_CONNECTION_STRING: "Host=db;Database=$POSTGRES_DB;Username=$POSTGRES_USER;Password=$POSTGRES_PASSWORD"
    restart: unless-stopped

  db:
    image: postgres:latest
    environment:
      POSTGRES_USER: $POSTGRES_USER
      POSTGRES_PASSWORD: $POSTGRES_PASSWORD
      POSTGRES_DB: $POSTGRES_DB
    volumes:
      - db-data:/var/lib/postgresql/data
    restart: unless-stopped

volumes:
  db-data:
