
name: Deploy to Dev

on:
  push:
    branches:
      - main

jobs:
  deploy-dev:
    runs-on: self-hosted
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Build Docker image
        run: docker build -t my-api-image .

      - name: Deploy and run migrations
        run: |
          docker compose -f docker-compose.yml down
          docker compose -f docker-compose.yml up -d
          docker compose exec app dotnet ef database update

      - name: Access API on host
        run: docker compose exec runner curl http://app:80/ # Access the API on the app container.

      - name: Clean up old images
        run: docker image prune -a -f
