name: Deploy
on:
  workflow_call:
    inputs:
      environment:
        type: string
        description: environment to deploy to
        required: true
jobs:
  deploy:
    environment: ${{ inputs.environment }}
    runs-on: self-hosted

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Create .env file
        run: |
          echo "POSTGRES_USER=${{ secrets.POSTGRES_USER }}" >> .env
          echo "POSTGRES_PASSWORD=${{ secrets.POSTGRES_PASSWORD }}" >> .env
          echo "POSTGRES_HOST=${{ secrets.POSTGRES_HOST }}" >> .env

          echo "POSTGRES_DB=${{ secrets.POSTGRES_DB }}" >> .env
          echo "DATABASE_CONNECTION_STRING=${{ secrets.DATABASE_CONNECTION_STRING }}" >> .env
          echo "LinkedInEmail=${{ secrets.LinkedInEmail }}" >> .env
          echo "LinkedInPass=${{ secrets.LinkedInPass }}" >> .env

      - name: Docker Compose Down
        run: docker compose down

      - name: Docker Compose Up
        run: docker compose --env-file .env up -d --build

      - name: Get Docker Compose Logs for Webcrawler on Failure
        if: failure()
        run: docker compose logs webcrawler --timestamps

