name: Deploy to Dev

on:
  push:
    branches:
      - dev

jobs:
  deploy:
    runs-on: self-hosted
    environment: Dev
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Docker Compose Down
        run: docker compose down
        working-directory: ./WebScraperDataIngestionAPI

      - name: Docker Compose Up
        run: |
          docker compose up -d \
            --build \
            --env-file <(echo "POSTGRES_USER=${{ secrets.POSTGRES_USER }}") \
            --env-file <(echo "POSTGRES_PASSWORD=${{ secrets.POSTGRES_PASSWORD }}") \
            --env-file <(echo "POSTGRES_DB=${{ secrets.POSTGRES_DB }}") \
            --env-file <(echo "DATABASE_CONNECTION_STRING=Host=db;Database=${{ secrets.POSTGRES_DB }};Username=${{ secrets.POSTGRES_USER }};Password=${{ secrets.POSTGRES_PASSWORD }}")
        working-directory: ./WebScraperDataIngestionAPI
