services:
  runner:
    build:
      context: .
      dockerfile: dockerfile-runner # Ensure this points to your runner's Dockerfile
    image: my-runner-image
    networks:
      - apprunner_network
    restart: unless-stopped

  app:
    build:
      context: .
      dockerfile: Dockerfile # Your API's Dockerfile
    image: my-api-image
    networks:
      - apprunner_network
    depends_on:
      - db
    environment:
      DATABASE_CONNECTION_STRING: "Host=db;Database=${{ secrets.POSTGRES_DB }};Username=${{ secrets.POSTGRES_USER }};Password=${{ secrets.POSTGRES_PASSWORD }}"
    restart: unless-stopped

  db: 
    image: postgres:latest
    environment:
      POSTGRES_USER: ${{ secrets.POSTGRES_USER }}
      POSTGRES_PASSWORD: ${{ secrets.POSTGRES_PASSWORD }}
      POSTGRES_DB: ${{ secrets.POSTGRES_DB }}
    volumes:
      - db-data:/var/lib/postgresql/data
    networks:
      - apprunner_network
    restart: unless-stopped

volumes:
  db-data:
