name: Deploy to Dev

on:
  push:
    branches:
      - main

jobs:

  deploy:
    runs-on: self-hosted
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Deploy to dev server
        uses: appleboy/ssh-action@v1.0.0
        with:
          host: ${{ secrets.DEV_SERVER_HOST }}
          username: ${{ secrets.DEV_SERVER_USER }}
          key: ${{ secrets.DEV_SERVER_KEY }}
          script: |
            cd /home/devuser/app/ # Adjust path as needed.
            docker compose -f docker-compose.yml down
            docker compose -f docker-compose.yml up -d
            docker compose exec app dotnet ef database update
            docker compose exec runner curl http://app:80/
            docker image prune -a -f
