name: Deploy to Dev

on:
  push:
    branches:
      - dev

jobs:

 deploy:
    runs-on: self-hosted

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Docker Compose Down
        run: docker compose down
        working-directory: ./WebScraperDataIngestionAPI

      - name: Docker Compose Up
        run: docker compose up -d
        working-directory: ./WebScraperDataIngestionAPI # Specify the subdirectory

      # - name: Health Check
      #   run: curl http://localhost:your_api_port/health

      # - name: Docker Logs
      #   run: docker logs your_api_container_name
