name: Deploy to Dev

on:
  push:
    branches:
      - dev

jobs:

  deploy:
    runs-on: self-hosted
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Debug secrets
        run: echo "DEV_SERVER_HOST: ${{ dev.DEV_SERVER_HOST }}"

      - name: Deploy to dev server
        uses: appleboy/ssh-action@v1.0.0
        with:
          host: ${{ dev.DEV_SERVER_HOST }}
          username: ${{ dev.DEV_SERVER_USER }}
          key: ${{ dev.DEV_SERVER_KEY }}
          script: |
            whoami
