name: Test And Deploy Dev
on:
  push:
    branches:
      - dev

jobs:
  runs-on: self-hosted
  environment: Dev
  test:

    uses: ./.github/workflows/test.yml
    deploy:

  deploy:
    needs: test
    uses: ./.github/workflows/deploy-dev.yml
