name: Run WebScraperDataIngestionApiTests

on:
  push:
    branches:
      - main 
  pull_request:
    branches:
      - main

jobs:
  test:
    runs-on: self-hosted 

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up .NET Core (if applicable)
        uses: actions/setup-dotnet@v4
        # https://github.com/actions/setup-dotnet/issues/327
        # container does not have permission to build in /usr/shared build in app directory instead
        # the app dir is defined in the docker file of my runner
        # i need to change that
        env:
          DOTNET_INSTALL_DIR: "/app/deps"
        with:
          dotnet-version: '8.0.x' 

      - name: Install dependencies (if applicable)
        run: dotnet restore WebScraperDataIngestionApiTests/WebScraperDataIngestionApiTests.csproj

      - name: Build project
        run: dotnet build WebScraperDataIngestionApiTests/WebScraperDataIngestionApiTests.csproj --configuration Release 

      - name: Run tests
        run: dotnet test WebScraperDataIngestionApiTests/WebScraperDataIngestionApiTests.csproj --configuration Release --no-build --verbosity normal
