name: Test And Deploy Dev
on:
  push:
    branches:
      - dev
jobs:
  test:
    uses: ./.github/workflows/test.yml # Corrected usage

  deploy:
    needs: test
    uses: ./.github/workflows/deploy.yml 

    secrets: inherit
    environment: Dev
